# Project: cleanning - [candy data]
### this notebook is for educational purpose . in this notebook we will do some cleanning

## Table of Contents
<ul>
<li><a href="#intro">Introduction</a></li>
<li><a href="#wrangling">wrangling</a></li>
  
</ul>

<a id='intro'></a>
## Introduction

### Dataset Description 

> i will go through candy data 2017 , this data has :
- Internal_ID
- Q1-Going Out?: Are you actually going trick or treating yourself? "has values `Yes or No`"
- Q2-Gender: It has four different options, `Femal ,Male ,Other ,I'd rather not say`
- Q3-Age: Numerical field
- Q4-Country: Text Field, but users have written their own version of the names. Example, for America, there are entries such as USA, us, US, America so we should consider that while cleanning
- Q5-State/Province: Text Field, but users have written their own version of the names. Same as the country data.
- Q6-Joy Or Despair: All kinds of chocolate bars are the questions with three distinct options to choose from (Joy, Meh, Despair).
- Q7-Joy Other: Text Field to write items not included above that give you JOY. Lots of missing values.
- Q8-Despair Other: Text Field ti write items not included above that give you DESPAIR. Lots of missing values.
- Q9-Other Comments: Text Field. Lots of missing values.
- Q10-Dress: Binary field. Missing values present
- Unnamed: 113
- Q11-Day: Binary Answer Field. Missing values present


In [1422]:
import warnings
warnings.filterwarnings(action='ignore')

# 1- import packages and load data

In [1423]:
# import requied libraries
import pandas as pd
import numpy as np  
import seaborn as sns
import matplotlib.pyplot as plt  
# load data
data = pd.read_excel("candyhierarchy2017.xlsx")
data.head()

Internal ID Q1: GOING OUT? Q2: GENDER Q3: AGE Q4: COUNTRY  \
0     90258773            NaN        NaN     NaN         NaN   
1     90272821             No       Male      44        USA    
2     90272829            NaN       Male      49         USA   
3     90272840             No       Male      40          us   
4     90272841             No       Male      23         usa   

  Q5: STATE, PROVINCE, COUNTY, ETC Q6 | 100 Grand Bar  \
0                              NaN                NaN   
1                               NM                MEH   
2                         Virginia                NaN   
3                               or                MEH   
4                         exton pa                JOY   

  Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes)  \
0                                                NaN                                       
1                                            DESPAIR                                       
2                                                NaN                                       
3                                            DESPAIR                                       
4                                            DESPAIR                                       

  Q6 | Any full-sized candy bar Q6 | Black Jacks  ... Q8: DESPAIR OTHER  \
0                           NaN              NaN  ...               NaN   
1                           JOY              MEH  ...               NaN   
2                           NaN              NaN  ...               NaN   
3                           JOY              MEH  ...               NaN   
4                           JOY          DESPAIR  ...               NaN   

                                  Q9: OTHER COMMENTS      Q10: DRESS  \
0                                                NaN             NaN   
1  Bottom line is Twix is really the only candy w...  White and gold   
2                                                NaN             NaN   
3                             Raisins can go to hell  White and gold   
4                                                NaN  White and gold   

  Unnamed: 113 Q11: DAY Q12: MEDIA [Daily Dish] Q12: MEDIA [Science]  \
0          NaN      NaN                     NaN                  NaN   
1          NaN   Sunday                     NaN                  1.0   
2          NaN      NaN                     NaN                  NaN   
3          NaN   Sunday                     NaN                  1.0   
4          NaN   Friday                     NaN                  1.0   

  Q12: MEDIA [ESPN] Q12: MEDIA [Yahoo] Click Coordinates (x, y)  
0               NaN                NaN                      NaN  
1               NaN                NaN                 (84, 25)  
2               NaN                NaN                      NaN  
3               NaN                NaN                 (75, 23)  
4               NaN                NaN                 (70, 10)  

[5 rows x 120 columns]

<a id='wrangling'></a>
## Data Wrangling



### General Properties

# 2- show some general properties for the data 

In [1424]:
data.shape

(2460, 120)

In [1425]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2460 entries, 0 to 2459
Columns: 120 entries, Internal ID to Click Coordinates (x, y)
dtypes: float64(4), int64(1), object(115)
memory usage: 2.3+ MB


In [1426]:
data.isnull().sum()

Internal ID                    0
Q1: GOING OUT?               110
Q2: GENDER                    41
Q3: AGE                       84
Q4: COUNTRY                   64
                            ... 
Q12: MEDIA [Daily Dish]     2375
Q12: MEDIA [Science]        1098
Q12: MEDIA [ESPN]           2361
Q12: MEDIA [Yahoo]          2393
Click Coordinates (x, y)     855
Length: 120, dtype: int64

In [1427]:
data.duplicated().sum()

0

# 3- write summary about what you get form the above functions
> #### tips : this summary can be about : if there is any missing values , if there a wrong data type , if there a wrong range of values , ....

In [1428]:
# there are many missing values in every column except  Internal ID  column
# wrong data type in age column it is string(object) must converted to numerical
# NO duplicated values

# cleaning

### 4- drop all the useless columns and  rows with too much NaN , 
> tip : useless columns can be like `Internal ID`and can be also columns with too much NaN 
- rename columns for easy access

In [1429]:
data.columns

Index(['Internal ID', 'Q1: GOING OUT?', 'Q2: GENDER', 'Q3: AGE', 'Q4: COUNTRY',
       'Q5: STATE, PROVINCE, COUNTY, ETC', 'Q6 | 100 Grand Bar',
       'Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes)',
       'Q6 | Any full-sized candy bar', 'Q6 | Black Jacks',
       ...
       'Q8: DESPAIR OTHER', 'Q9: OTHER COMMENTS', 'Q10: DRESS', 'Unnamed: 113',
       'Q11: DAY', 'Q12: MEDIA [Daily Dish]', 'Q12: MEDIA [Science]',
       'Q12: MEDIA [ESPN]', 'Q12: MEDIA [Yahoo]', 'Click Coordinates (x, y)'],
      dtype='object', length=120)

In [1430]:
data = data.rename(columns = {'Q1: GOING OUT?' : 'going_out', 'Q2: GENDER' : 'gender', 'Q3: AGE': 'age', 'Q4: COUNTRY' : 'country',
       'Q5: STATE, PROVINCE, COUNTY, ETC' : 'state', 'Q10: DRESS' : 'dress', 'Q11: DAY': 'day',
       'Q12: MEDIA [Daily Dish]' : 'media_DailyDish', 'Q12: MEDIA [Science]': 'media_Science', 'Q12: MEDIA [ESPN]' : 'media_ESPN',
       'Q12: MEDIA [Yahoo]': 'media_Yahoo', 'Q8: DESPAIR OTHER':'despair_other', 'Q9: OTHER COMMENTS':'other_comments'})
data = data.rename(columns ={'Q6 | 100 Grand Bar':'100_grand_bar','Q6 | Any full-sized candy bar':'any_full_sized_candy_bar','Q6 | Black Jacks':'black_jacks','Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes)':'anonymous_brown_globs_that_come_in_black_and_orange_wrappers'})

In [1431]:
data.columns

Index(['Internal ID', 'going_out', 'gender', 'age', 'country', 'state',
       '100_grand_bar',
       'anonymous_brown_globs_that_come_in_black_and_orange_wrappers',
       'any_full_sized_candy_bar', 'black_jacks',
       ...
       'despair_other', 'other_comments', 'dress', 'Unnamed: 113', 'day',
       'media_DailyDish', 'media_Science', 'media_ESPN', 'media_Yahoo',
       'Click Coordinates (x, y)'],
      dtype='object', length=120)

In [1432]:
# dropping useless columns and columns with many missing values
data= data.drop(['Internal ID' ,'Unnamed: 113','Click Coordinates (x, y)','media_DailyDish','media_Science','media_ESPN','media_Yahoo','Q7: JOY OTHER','despair_other','other_comments'
] , axis=1)

In [1433]:
data.head()

going_out gender  age country     state 100_grand_bar  \
0       NaN    NaN  NaN     NaN       NaN           NaN   
1        No   Male   44    USA         NM           MEH   
2       NaN   Male   49     USA  Virginia           NaN   
3        No   Male   40      us        or           MEH   
4        No   Male   23     usa  exton pa           JOY   

  anonymous_brown_globs_that_come_in_black_and_orange_wrappers  \
0                                                NaN             
1                                            DESPAIR             
2                                                NaN             
3                                            DESPAIR             
4                                            DESPAIR             

  any_full_sized_candy_bar black_jacks Q6 | Bonkers (the candy)  ...  \
0                      NaN         NaN                      NaN  ...   
1                      JOY         MEH                  DESPAIR  ...   
2                      NaN         NaN                      NaN  ...   
3                      JOY         MEH                      MEH  ...   
4                      JOY     DESPAIR                      MEH  ...   

  Q6 | Trail Mix Q6 | Twix  \
0            NaN       NaN   
1        DESPAIR       JOY   
2            NaN       NaN   
3            MEH       JOY   
4        DESPAIR       JOY   

  Q6 | Vials of pure high fructose corn syrup, for main-lining into your vein  \
0                                                NaN                            
1                                            DESPAIR                            
2                                                NaN                            
3                                            DESPAIR                            
4                                                MEH                            

  Q6 | Vicodin Q6 | Whatchamacallit Bars Q6 | White Bread  \
0          NaN                       NaN              NaN   
1      DESPAIR                   DESPAIR          DESPAIR   
2          NaN                       NaN              NaN   
3          JOY                       JOY          DESPAIR   
4          JOY                       JOY          DESPAIR   

  Q6 | Whole Wheat anything Q6 | York Peppermint Patties           dress  \
0                       NaN                          NaN             NaN   
1                   DESPAIR                      DESPAIR  White and gold   
2                       NaN                          NaN             NaN   
3                   DESPAIR                      DESPAIR  White and gold   
4                   DESPAIR                          JOY  White and gold   

      day  
0     NaN  
1  Sunday  
2     NaN  
3  Sunday  
4  Friday  

[5 rows x 110 columns]

In [1434]:
data.isnull().sum()

going_out                       110
gender                           41
age                              84
country                          64
state                           100
                               ... 
Q6 | White Bread                757
Q6 | Whole Wheat anything       747
Q6 | York Peppermint Patties    705
dress                           744
day                             725
Length: 110, dtype: int64

### 5 - clean `going out` column 
> tip : you should choose which best value to put in place of these NaNs ( mode, unknown,other ....etc)

In [1435]:
data['going_out'].unique()

array([nan, 'No', 'Yes'], dtype=object)

In [1436]:
data['going_out'].mode()

0    No
Name: going_out, dtype: object

In [1437]:
# fill missing values with mode because it is category
data['going_out'] = data['going_out'].fillna('No')

In [1438]:
# checking
data['going_out'].unique()

array(['No', 'Yes'], dtype=object)

In [1439]:
# checking
data['going_out'].isnull().sum()

0

### 6 - clean ` gender` column 
> tip : you should choose which best value to put in place of these NaNs ( mode, unknown,other ....etc)

In [1440]:
data.isnull().sum()

going_out                         0
gender                           41
age                              84
country                          64
state                           100
                               ... 
Q6 | White Bread                757
Q6 | Whole Wheat anything       747
Q6 | York Peppermint Patties    705
dress                           744
day                             725
Length: 110, dtype: int64

In [1441]:
data['gender'].unique()

array([nan, 'Male', 'Female', "I'd rather not say", 'Other'], dtype=object)

In [1442]:
data['gender'].mode()

0    Male
Name: gender, dtype: object

In [1443]:
data['gender'] = data['gender'].fillna('Male')

In [1444]:
# check
data['gender'].isnull().sum()

0

### 7 - clean ` age` column 
> tip : note the type of age column , and NaN values
 - try to use `to_numeric` 
 - tip : you should choose which best value to put in place of these NaNs ( mean, median, ....etc)

In [1445]:
data['age'].unique()

array([nan, 44, 49, 40, 23, 53, 33, 43, 56, 64, 37, 59, 48, 54, 36, 45,
       25, 34, 35, 38, 58, 50, 47, 16, 52, 63, 65, 41, 27, 31, 61, 46, 42,
       62, 29, 39, 32, 28, 69, 67, 30, 22, 26, 51, 70, 24, 18, 19,
       'Old enough', 57, 60, 66, 12, 'Many', 55, 72, '?', 21, 11, 'no', 9,
       68, 20, 6, 10, 71, 90, 13, '45-55', 312, 99, 7, 'hahahahaha', 88,
       39.4, 74, 102, 'older than dirt', 17, 15, 8, 75, '5u', 'Enough',
       'See question 2', '24-50', 14, 'Over 50', 100, 76, 1000,
       'sixty-nine', '46 Halloweens.', 'ancient', 77, 'OLD', 'old', 73,
       70.5, 1, 'MY NAME JEFF', 4, '59 on the day after Halloween',
       'old enough', 'your mom',
       'I can remember when Java was a cool new language', '60+'],
      dtype=object)

In [1446]:
# convert type column from object to numerical
data['age'] = pd.to_numeric(data['age'], errors='coerce')

In [1447]:
# there are outliers such as {1000,312} so i will use median not mean
data['age'].median()

41.0

In [1448]:
data['age'] = data['age'].fillna(41.0)

In [1449]:
data['age'] = pd.to_numeric(data['age'], errors='coerce')

In [1450]:
data['age'].isnull().sum()

0

# 8 - clean country column

    tip : note that country column has country names with different writing ways

    use fuzzywuzzy to deal with this problem
    you should choose which best value to put in place of these NaNs ( mode, unknown,other ....etc)



In [1451]:
data['country'].unique()

array([nan, 'USA ', 'USA', 'us', 'usa', 'canada', 'Canada', 'Us', 'US',
       'Murica', 'United States', 'uk', 'United Kingdom', 'united states',
       'Usa', 'United States ', 'United staes',
       'United States of America', 'UAE', 'England', 'UK', 'canada ',
       'Mexico', 'United states', 'u.s.a.', 'USAUSAUSA', 'america', 35,
       'france', 'United States of America ', 'U.S.A.', 'finland',
       'unhinged states', 'Canada ', 'united states of america',
       'US of A', 'Unites States', 'The United States', 'North Carolina ',
       'Unied States', 'Netherlands', 'germany', 'Europe', 'Earth', 'U S',
       'u.s.', 'U.K. ', 'Costa Rica', 'The United States of America',
       'unite states', 'U.S.', 46, 'cascadia', 'Australia',
       'insanity lately', 'Greece', 'USA? Hard to tell anymore..',
       "'merica", 'usas', 'Pittsburgh', 45, 'United State', 32, 'France',
       'australia', 'A', 'Can', 'Canae', 'New York', 'Trumpistan',
       'Ireland', 'United Sates', 'Korea', 

In [1452]:
# fuzzywazzy made eror i used another way

In [1453]:
# convert to lower case
data['country'] = data['country'].str.lower()
# remove trailing white spaces
data['country'] = data['country'].str.strip()

In [1454]:
# for USA
set([x for x in data['country'] if 'u' in str(x)]) 

{'australia',
 'europe',
 'i pretend to be from canada, but i am really from the united states.',
 'murica',
 'murrika',
 'pittsburgh',
 'south africa',
 'south korea',
 'soviet canuckistan',
 'subscribe to dm4uz3 on youtube',
 'the united states',
 'the united states of america',
 'trumpistan',
 'u s',
 'u s a',
 'u.k.',
 'u.s.',
 'u.s.a.',
 'uae',
 'ud',
 'uk',
 'unhinged states',
 'unied states',
 'unite states',
 'united kingdom',
 'united sates',
 'united staes',
 'united state',
 'united statea',
 'united stated',
 'united states',
 'united states of america',
 'united statss',
 'united ststes',
 'unites states',
 'us',
 'us of a',
 'usa',
 'usa usa usa!!!!',
 'usa! usa! usa!',
 'usa? hard to tell anymore..',
 'usaa',
 'usas',
 'usausausa',
 'ussa'}

In [1455]:
USA = [x for x in data['country'] if (('u' in str(x) or 'U' in str(x)) and 'ingdom' not in str(x)\
     and 'urope' not in str(x) and 'stralia' not in str(x) and 'South Korea' not in str(x) and 'South africa' not in str(x) and 'uk' not in str(x))]

In [1456]:
data['country'] = data['country'].replace(to_replace = USA, value = 'USA')

In [1457]:
data['country'].value_counts()

USA                     2042
canada                   224
uk                        18
united kingdom            14
germany                   10
australia                  7
netherlands                6
america                    6
japan                      5
scotland                   5
mexico                     4
ireland                    4
france                     3
switzerland                3
sweden                     2
china                      2
denmark                    2
hong kong                  2
singapore                  1
n. america                 1
alaska                     1
narnia                     1
endland                    1
the netherlands            1
indonesia                  1
taiwan                     1
new jersey                 1
i don't know anymore       1
ahem....amerca             1
spain                      1
atlantis                   1
korea                      1
canada`                    1
iceland                    1
england       

In [1458]:
data['country']=data['country'].replace('uk','united kingdom')

In [1459]:
data['country'].value_counts()

USA                     2042
canada                   224
united kingdom            32
germany                   10
australia                  7
america                    6
netherlands                6
japan                      5
scotland                   5
mexico                     4
ireland                    4
switzerland                3
france                     3
sweden                     2
hong kong                  2
china                      2
denmark                    2
indonesia                  1
ahem....amerca             1
narnia                     1
new jersey                 1
i don't know anymore       1
atlantis                   1
the netherlands            1
endland                    1
alaska                     1
singapore                  1
taiwan                     1
spain                      1
n. america                 1
korea                      1
canada`                    1
iceland                    1
england                    1
finland       

In [1460]:
data['country'].unique()

array([nan, 'USA', 'canada', 'united kingdom', 'england', 'mexico',
       'america', 'france', 'finland', 'north carolina', 'netherlands',
       'germany', 'europe', 'earth', 'costa rica', 'cascadia',
       'australia', 'insanity lately', 'greece', "'merica", 'a', 'can',
       'canae', 'new york', 'ireland', 'korea', 'california', 'japan',
       'iceland', 'canada`', 'scotland', 'denmark', 'switzerland',
       'ahem....amerca', 'new jersey', 'indonesia', 'the netherlands',
       'endland', 'atlantis', 'alaska', 'n. america', 'singapore',
       'china', 'taiwan', 'hong kong', 'spain', 'sweden', 'narnia',
       "i don't know anymore", 'fear and loathing'], dtype=object)

In [1461]:
# replace unusual values with USA bec it is the  mode  
#correct america values
data['country']=data['country'].replace({'a':'USA','can':'USA','ahem....amerca':'america',"i don't know anymore":"USA",'fear and loathing':'USA','earth':'USA',"'merica":"america",'n. america':'america','insanity lately':'USA'})

In [1462]:
data['country'].unique()

array([nan, 'USA', 'canada', 'united kingdom', 'england', 'mexico',
       'america', 'france', 'finland', 'north carolina', 'netherlands',
       'germany', 'europe', 'costa rica', 'cascadia', 'australia',
       'greece', 'canae', 'new york', 'ireland', 'korea', 'california',
       'japan', 'iceland', 'canada`', 'scotland', 'denmark',
       'switzerland', 'new jersey', 'indonesia', 'the netherlands',
       'endland', 'atlantis', 'alaska', 'singapore', 'china', 'taiwan',
       'hong kong', 'spain', 'sweden', 'narnia'], dtype=object)

In [1463]:
# also correcting other values
data['country']=data['country'].replace({'the netherlands':'netherlands','canada`':'canada','north carolina':'california','endland':'england','europe':'USA'})

In [1464]:
data['country'].unique() # NOW its better

array([nan, 'USA', 'canada', 'united kingdom', 'england', 'mexico',
       'america', 'france', 'finland', 'california', 'netherlands',
       'germany', 'costa rica', 'cascadia', 'australia', 'greece',
       'canae', 'new york', 'ireland', 'korea', 'japan', 'iceland',
       'scotland', 'denmark', 'switzerland', 'new jersey', 'indonesia',
       'atlantis', 'alaska', 'singapore', 'china', 'taiwan', 'hong kong',
       'spain', 'sweden', 'narnia'], dtype=object)

In [1465]:
# fill missing values with column mode << USA
data['country'] = data['country'].fillna('USA')

In [1466]:
# checking
data['country'].isnull().sum()

0

### 9 - clean ` area` column
> tip : area column has the same problem as country columns , but looking at all it's unique values may give us another way to deal with it rather than try to fix it

In [1467]:
data['state'].unique()

array([nan, 'NM', 'Virginia', 'or', 'exton pa', 'Colorado ', 'ontario',
       'Ontario', 'Wa', 'Quebec', 'NY', 'California', 'Texas', 'NEW YORK',
       'CO', 'IN', 'MN', 'aberdeenshire', 'Alberta', 'Wisconsin, 53705',
       'RI', 'NC', 'Scotland', 'minnesota', 'Michigan', 'Florida',
       'New Jersey', 'VA', 'Colorado', 'Los Angeles, California', 'CA',
       'New York ', 'Chicago, Illinois', 'Nj', 'Wisconsin', 'Minnesota ',
       'London', 'mn', 'TEXAS', 'Illinois', 'District of Columbia',
       'Washington', 'Massachusetts ', 'OR', 'Montana', 'New York',
       'massachusetts', 'Abu Dhabi', 'TX', 'Arizona', 'Dc', 'yukon',
       'Pennsylvania ', 'MD', 'Ohio', 'Alberta ', 'OXFORDSHIRE', 'DC',
       'Iowa', 'Mn', 'TN', 'BC', 'Maryland', 'MI', 'Wisconsin ', 'alaska',
       'Ny', 'Colorado, Jefferson county ', 'Louisiana', 'pa',
       'CO, Larimer County', 'Nebraska ', 'Oregon', 'UT', 'ny',
       'Pennsylvania', 'CDMX', 'north carolina', 'Tennessee ', 'Texas ',
       'Knox cou

In [1468]:
# convert to lower case
data['state'] = data['state'].str.lower()
# remove trailing white spaces
data['state'] = data['state'].str.strip()

In [1470]:
data['state'].value_counts()

california              171
ca                      128
ontario                  79
illinois                 72
texas                    71
                       ... 
greater manchester        1
fife, scotland            1
a                         1
kalamazoo county, mi      1
psychotic                 1
Name: state, Length: 329, dtype: int64

In [1471]:
data['state']=data['state'].replace({'ca':'california','ny':'newyork','ne':'newyork','oregon - but will be in washington for halloween':'washington'})

In [1472]:
data['state'].unique()

array([nan, 'nm', 'virginia', 'or', 'exton pa', 'colorado', 'ontario',
       'wa', 'quebec', 'newyork', 'california', 'texas', 'new york', 'co',
       'in', 'mn', 'aberdeenshire', 'alberta', 'wisconsin, 53705', 'ri',
       'nc', 'scotland', 'minnesota', 'michigan', 'florida', 'new jersey',
       'va', 'los angeles, california', 'chicago, illinois', 'nj',
       'wisconsin', 'london', 'illinois', 'district of columbia',
       'washington', 'massachusetts', 'montana', 'abu dhabi', 'tx',
       'arizona', 'dc', 'yukon', 'pennsylvania', 'md', 'ohio',
       'oxfordshire', 'iowa', 'tn', 'bc', 'maryland', 'mi', 'alaska',
       'colorado, jefferson county', 'louisiana', 'pa',
       'co, larimer county', 'nebraska', 'oregon', 'ut', 'cdmx',
       'north carolina', 'tennessee', 'knox county, tennessee',
       'new mexico', 'maine', 'virginia, arlington', 'mo', 'ma',
       'new york, ny', 'il', 'new hampshire', 'georgia',
       'washington, clark', 'oklahoma', 'sc', 'nevada', 'vancouve

In [1473]:
data['state'].mode()

0    california
Name: state, dtype: object

In [1474]:
set([x for x in data['country'] if 'c' in str(x)]) 

{'america',
 'california',
 'canada',
 'canae',
 'cascadia',
 'china',
 'costa rica',
 'france',
 'greece',
 'iceland',
 'mexico',
 'scotland'}

In [1475]:
calif = [x for x in data['state'] if (('c' in str(x) or 'c' in str(x)) and 'chig' not in str(x)\
     and 'couny' not in str(x) and 'cuy' not in str(x) and 'col' not in str(x) )]

In [1476]:
data['state'] = data['state'].replace(to_replace = calif, value = 'california')

In [1477]:
data['state'].unique()

array([nan, 'nm', 'virginia', 'or', 'exton pa', 'colorado', 'ontario',
       'wa', 'california', 'newyork', 'texas', 'new york', 'in', 'mn',
       'aberdeenshire', 'alberta', 'ri', 'minnesota', 'michigan',
       'florida', 'new jersey', 'va', 'nj', 'london', 'illinois',
       'district of columbia', 'washington', 'montana', 'abu dhabi', 'tx',
       'arizona', 'yukon', 'pennsylvania', 'md', 'ohio', 'oxfordshire',
       'iowa', 'tn', 'maryland', 'mi', 'alaska',
       'colorado, jefferson county', 'louisiana', 'pa', 'nebraska',
       'oregon', 'ut', 'tennessee', 'maine', 'virginia, arlington', 'mo',
       'ma', 'new york, ny', 'il', 'new hampshire', 'georgia', 'oklahoma',
       'nevada', 'washington, king', 'rhode island', 'alabama', 'ga',
       'nope', 'manitoba', 'north dakota', 'astoria ny', 'kansas', 'sk',
       'missouri', 'british columbia', 'west virginia', 'usa',
       'philadelphia', 'hi', 'south holland', 'derbyshire', 'hesse', 'vt',
       'utah', 'fl', 'michigan, 

In [1478]:
data['state'].value_counts()

california           655
ontario               79
illinois              72
texas                 71
oregon                62
                    ... 
colorado, boulder      1
new orleans la         1
qld                    1
brooklyn               1
st louis mo            1
Name: state, Length: 209, dtype: int64

In [1479]:
set([x for x in data['state'] if 'n' in str(x)]) 

{'aberdeenshire',
 'alaska, matanuska-susitna borough',
 'arizona',
 'arkansas',
 'arlington, va',
 'astoria ny',
 'atlanta, ga',
 'berlin',
 'bloomington, in',
 'british columbia, canada',
 'brooklyn',
 'california',
 'colorado larimer county',
 'colorado, jefferson county',
 'cuyahoga county, ohio',
 'devonshire',
 'dublin',
 'edinburgh',
 'exton pa',
 'greater london',
 'hessen',
 'hong kong',
 'illinois',
 'in',
 'indiana',
 'kanagawa',
 'kansas',
 'kent',
 'kings, new york',
 'kwazulu-natal',
 'londom',
 'london',
 'louisiana',
 'maine',
 'manitoba',
 'mannheim, baden-württemberg',
 'marne',
 'maryland',
 'merlin',
 'michigan',
 'michigan, shiawassee county',
 'michigin',
 'midlothian',
 'minnesota',
 'mn',
 'montana',
 'munster',
 'n-brabant',
 'na',
 nan,
 'nb',
 'nd',
 'nebraska',
 'nevada',
 'new hampshire',
 'new jersey',
 'new orleans la',
 'new york',
 'new york, new york',
 'new york, ny',
 'newfoundland',
 'newfoundland and labrador',
 'newyork',
 'nh',
 'nj',
 'nj; essex

In [1480]:
ney = [x for x in data['state'] if (('n' in str(x) or 'n' in str(x)) and 'wash' not in str(x)\
     and 'wash')]

In [1481]:
data['state'] = data['state'].replace(to_replace = ney, value = 'newyork')

In [1482]:
data['state'].unique()

array(['newyork', 'or', 'colorado', 'wa', 'texas', 'alberta', 'ri',
       'florida', 'va', 'district of columbia', 'washington', 'abu dhabi',
       'tx', 'md', 'ohio', 'oxfordshire', 'iowa', 'mi', 'alaska', 'pa',
       'ut', 'mo', 'ma', 'il', 'georgia', 'oklahoma', 'washington, king',
       'alabama', 'ga', 'sk', 'missouri', 'british columbia', 'usa',
       'philadelphia', 'hi', 'derbyshire', 'hesse', 'vt', 'utah', 'fl',
       'idaho ada', 'la', 'hawaii', 'az', 'sub earth', 'ab',
       'washington state', 'sussex', 'mississippi', 'oh',
       'washington, seattle, king', 'pittsburgh pa', 'mt', 'ks',
       'albeqrrta', 'qld', 'ky', 'colorado, boulder', 'a', 'wi', 'wv',
       'ms', 'kildare', 'tehama', 'sd', 'missoure', 'ia', 'tokyo',
       'idaho', 'bristol', 'ørbæk', 'pr', 'idf', 'osaka', 'surrey',
       'vaud', 'glasgow', 'seoul', 'the shore', 'tx.', 'jakarta',
       'rotterdam', 'ar', 'greifswald', 'south dakota', 'ga - georgia',
       'colorado (co)', 'ut, salt lake', '

In [1483]:
set([x for x in data['state'] if 'w' in str(x)]) 

{'delaware',
 'glasgow',
 'greifswald',
 'hawaii',
 'iowa',
 'newyork',
 'wa',
 'washingto',
 'washington',
 'washington state',
 'washington, king',
 'washington, seattle, king',
 'west yorkshire',
 'wi',
 'wv'}

In [1484]:
wash= [x for x in data['state'] if (('w' in str(x) or 'w' in str(x)) and 'new' not in str(x)\
     and 'hai')]

In [1485]:
data['state'] = data['state'].replace(to_replace = wash, value = 'washington')

In [1486]:
data['state'].unique()

array(['newyork', 'or', 'colorado', 'washington', 'texas', 'alberta',
       'ri', 'florida', 'va', 'district of columbia', 'abu dhabi', 'tx',
       'md', 'ohio', 'oxfordshire', 'mi', 'alaska', 'pa', 'ut', 'mo',
       'ma', 'il', 'georgia', 'oklahoma', 'alabama', 'ga', 'sk',
       'missouri', 'british columbia', 'usa', 'philadelphia', 'hi',
       'derbyshire', 'hesse', 'vt', 'utah', 'fl', 'idaho ada', 'la', 'az',
       'sub earth', 'ab', 'sussex', 'mississippi', 'oh', 'pittsburgh pa',
       'mt', 'ks', 'albeqrrta', 'qld', 'ky', 'colorado, boulder', 'a',
       'ms', 'kildare', 'tehama', 'sd', 'missoure', 'ia', 'tokyo',
       'idaho', 'bristol', 'ørbæk', 'pr', 'idf', 'osaka', 'surrey',
       'vaud', 'seoul', 'the shore', 'tx.', 'jakarta', 'rotterdam', 'ar',
       'south dakota', 'ga - georgia', 'colorado (co)', 'ut, salt lake',
       'madrid', 'philadelphia, pa', 'philadelphia pa', 'ok', 'ill',
       'ur mom', 'marietta, ga', 'st louis mo'], dtype=object)

In [1487]:
# correcting unusl valus
data['state'] = data['state'].replace({'sub earth':'california','usa':'california','ørbæk':'california','ur mom':'california','ill':'california','ok':'california'})

In [1488]:
data['state'].unique()

array(['newyork', 'or', 'colorado', 'washington', 'texas', 'alberta',
       'ri', 'florida', 'va', 'district of columbia', 'abu dhabi', 'tx',
       'md', 'ohio', 'oxfordshire', 'mi', 'alaska', 'pa', 'ut', 'mo',
       'ma', 'il', 'georgia', 'oklahoma', 'alabama', 'ga', 'sk',
       'missouri', 'british columbia', 'california', 'philadelphia', 'hi',
       'derbyshire', 'hesse', 'vt', 'utah', 'fl', 'idaho ada', 'la', 'az',
       'ab', 'sussex', 'mississippi', 'oh', 'pittsburgh pa', 'mt', 'ks',
       'albeqrrta', 'qld', 'ky', 'colorado, boulder', 'a', 'ms',
       'kildare', 'tehama', 'sd', 'missoure', 'ia', 'tokyo', 'idaho',
       'bristol', 'pr', 'idf', 'osaka', 'surrey', 'vaud', 'seoul',
       'the shore', 'tx.', 'jakarta', 'rotterdam', 'ar', 'south dakota',
       'ga - georgia', 'colorado (co)', 'ut, salt lake', 'madrid',
       'philadelphia, pa', 'philadelphia pa', 'marietta, ga',
       'st louis mo'], dtype=object)

In [1489]:
set([x for x in data['country'] if 'm' in str(x)]) 

{'america', 'denmark', 'germany', 'mexico', 'united kingdom'}

In [1490]:
mad= [x for x in data['state'] if (('m' in str(x) or 'm' in str(x)) and 'ger' not in str(x)\
     and 'rica' not in str(x) and 'den' not in str(x) and 'united kingdom' not in str(x) and 'mexico' not in str(x) and 'america' not in str(x))]

In [1491]:
data['state'] = data['state'].replace(to_replace = mad, value = 'madrid')

In [1492]:
data['state'].unique()

array(['newyork', 'or', 'colorado', 'washington', 'texas', 'alberta',
       'ri', 'florida', 'va', 'madrid', 'abu dhabi', 'tx', 'ohio',
       'oxfordshire', 'alaska', 'pa', 'ut', 'il', 'georgia', 'ga', 'sk',
       'california', 'philadelphia', 'hi', 'derbyshire', 'hesse', 'vt',
       'utah', 'fl', 'idaho ada', 'la', 'az', 'ab', 'sussex', 'oh',
       'pittsburgh pa', 'ks', 'albeqrrta', 'qld', 'ky',
       'colorado, boulder', 'a', 'kildare', 'sd', 'ia', 'tokyo', 'idaho',
       'bristol', 'pr', 'idf', 'osaka', 'surrey', 'vaud', 'seoul',
       'the shore', 'tx.', 'jakarta', 'ar', 'south dakota',
       'ga - georgia', 'colorado (co)', 'ut, salt lake',
       'philadelphia, pa', 'philadelphia pa'], dtype=object)

In [1493]:
data['state'] = data['state'].replace({'pa':'philadelphia','philadelphia pa':'philadelphia','pittsburgh pa':'philadelphia','philadelphia, pa':'philadelphia'})

In [1494]:
data['state'].unique()

array(['newyork', 'or', 'colorado', 'washington', 'texas', 'alberta',
       'ri', 'florida', 'va', 'madrid', 'abu dhabi', 'tx', 'ohio',
       'oxfordshire', 'alaska', 'philadelphia', 'ut', 'il', 'georgia',
       'ga', 'sk', 'california', 'hi', 'derbyshire', 'hesse', 'vt',
       'utah', 'fl', 'idaho ada', 'la', 'az', 'ab', 'sussex', 'oh', 'ks',
       'albeqrrta', 'qld', 'ky', 'colorado, boulder', 'a', 'kildare',
       'sd', 'ia', 'tokyo', 'idaho', 'bristol', 'pr', 'idf', 'osaka',
       'surrey', 'vaud', 'seoul', 'the shore', 'tx.', 'jakarta', 'ar',
       'south dakota', 'ga - georgia', 'colorado (co)', 'ut, salt lake'],
      dtype=object)

In [1495]:
data['state'] = data['state'].replace({'or':'colorado','oh':'ohio','colorado (co)':'colorado','tx':'texas','ga':'georgia','ga - georgia':'georgia','tx.':'texas','south dakota':'california','surrey':'california','vaud':"california",'the shore':'california'})

In [1496]:
data['state'] = data['state'].replace({'hi':'ohio','a':'ohio','il':'ohio','idaho':'ohio','ar':'ohio','ia':'ohio','ri':'georgia','va':'philadelphia','vt':'philadelphia','fl':'florida','la':'florida','ks':'tokyo','sk':'tokyo','ky':'tokyo','ut':'california','az':'california','ab':'california','sd':'california','pr':'california','ut, salt lake':'california','idf':'california','qld':'california'})

In [1497]:
data['state'].unique()

array(['newyork', 'colorado', 'washington', 'texas', 'alberta', 'georgia',
       'florida', 'philadelphia', 'madrid', 'abu dhabi', 'ohio',
       'oxfordshire', 'alaska', 'california', 'tokyo', 'derbyshire',
       'hesse', 'utah', 'idaho ada', 'sussex', 'albeqrrta',
       'colorado, boulder', 'kildare', 'bristol', 'osaka', 'seoul',
       'jakarta'], dtype=object)

In [1498]:
data['state'].isnull().sum()

0

### 10 - clean ` Q6` columns
>- tip : Q6 has all kinds of chocolate bars and questions with three distinct options to choose from (Joy, Meh, Despair).
- so all the column that has Q6 is a candy name , so you should go through all these column and you should choose which best value to put in place of these NaNs ( mode, unknown,other ....etc)

In [1499]:
data.columns

Index(['going_out', 'gender', 'age', 'country', 'state', '100_grand_bar',
       'anonymous_brown_globs_that_come_in_black_and_orange_wrappers',
       'any_full_sized_candy_bar', 'black_jacks', 'Q6 | Bonkers (the candy)',
       ...
       'Q6 | Trail Mix', 'Q6 | Twix',
       'Q6 | Vials of pure high fructose corn syrup, for main-lining into your vein',
       'Q6 | Vicodin', 'Q6 | Whatchamacallit Bars', 'Q6 | White Bread',
       'Q6 | Whole Wheat anything', 'Q6 | York Peppermint Patties', 'dress',
       'day'],
      dtype='object', length=110)

In [1500]:
data.mode()

going_out gender   age country    state 100_grand_bar  \
0        No   Male  41.0     USA  newyork           JOY   

  anonymous_brown_globs_that_come_in_black_and_orange_wrappers  \
0                                            DESPAIR             

  any_full_sized_candy_bar black_jacks Q6 | Bonkers (the candy)  ...  \
0                      JOY     DESPAIR                      MEH  ...   

  Q6 | Trail Mix Q6 | Twix  \
0        DESPAIR       JOY   

  Q6 | Vials of pure high fructose corn syrup, for main-lining into your vein  \
0                                            DESPAIR                            

  Q6 | Vicodin Q6 | Whatchamacallit Bars Q6 | White Bread  \
0      DESPAIR                       JOY          DESPAIR   

  Q6 | Whole Wheat anything Q6 | York Peppermint Patties           dress  \
0                   DESPAIR                          JOY  White and gold   

      day  
0  Friday  

[1 rows x 110 columns]

In [1501]:
# Q6 :questions on chocolate 
# fill NAN for every column with column mode
data['100_grand_bar'] = data['100_grand_bar'].fillna('JOY')
data['anonymous_brown_globs_that_come_in_black_and_orange_wrappers'] = data['anonymous_brown_globs_that_come_in_black_and_orange_wrappers'].fillna('DESPAIR')
data['any_full_sized_candy_bar'] = data['any_full_sized_candy_bar'].fillna('JOY')
data['black_jacks'] = data['black_jacks'].fillna('DESPAIR')
data['Q6 | Trail Mix'] = data['Q6 | Trail Mix'].fillna('MESH')
data['Q6 | Trail Mix'] = data['Q6 | Trail Mix'].fillna('DESPAIR')
data['Q6 | Twix'] = data['Q6 | Twix'].fillna('JOY')
data['Q6 | Vials of pure high fructose corn syrup, for main-lining into your vein'] = data['Q6 | Vials of pure high fructose corn syrup, for main-lining into your vein'].fillna('DESPAIR')
data['Q6 | Vicodin'] = data['Q6 | Vicodin'].fillna('DESPAIR')
data['Q6 | Whatchamacallit Bars'] = data['Q6 | Whatchamacallit Bars'].fillna('JOY')
data['Q6 | White Bread'] = data['Q6 | White Bread'].fillna('DESPAIR')
data['Q6 | Whole Wheat anything'] = data['Q6 | Whole Wheat anything'].fillna('DESPAIR')
data['Q6 | York Peppermint Patties'] = data['Q6 | York Peppermint Patties'].fillna('JOY')


### 11 - clean ` dress` column
>tip : you should choose which best value to put in place of these NaNs ( mode, unknown,other ....etc)

In [1502]:
data['dress'].unique()

array([nan, 'White and gold', 'Blue and black'], dtype=object)

In [1503]:
data['dress'].isnull().sum()

744

In [1504]:
data['dress'].mode()

0    White and gold
Name: dress, dtype: object

In [1505]:
data['dress'] = data['dress'].fillna('White and gold')

In [1506]:
data['dress'].unique()

array(['White and gold', 'Blue and black'], dtype=object)

In [1507]:
data['dress'].isnull().sum()

0

### 12 - clean ` day` column
>tip : you should choose which best value to put in place of these NaNs ( mode, unknown,other ....etc)

In [1508]:
data['day'].unique()

array([nan, 'Sunday', 'Friday'], dtype=object)

In [1509]:
data['day'].isnull().sum()

725

In [1510]:
data['day'].mode()

0    Friday
Name: day, dtype: object

In [1511]:
data['day'] = data['day'].fillna('Friday')

### 13 - check
> after finish cleaning you should make sure your data is clean and that :
- there is no wrong data type
- there is no NaN values 
- all the column are cleaing and ready for the next step `EDA`

In [1512]:
data.isnull().sum()

going_out                       0
gender                          0
age                             0
country                         0
state                           0
                               ..
Q6 | White Bread                0
Q6 | Whole Wheat anything       0
Q6 | York Peppermint Patties    0
dress                           0
day                             0
Length: 110, dtype: int64

In [1513]:
data.dtypes

going_out                        object
gender                           object
age                             float64
country                          object
state                            object
                                 ...   
Q6 | White Bread                 object
Q6 | Whole Wheat anything        object
Q6 | York Peppermint Patties     object
dress                            object
day                              object
Length: 110, dtype: object

In [1514]:
data.head()

going_out gender   age country     state 100_grand_bar  \
0        No   Male  41.0     USA   newyork           JOY   
1        No   Male  44.0     USA   newyork           MEH   
2        No   Male  49.0     USA   newyork           JOY   
3        No   Male  40.0     USA  colorado           MEH   
4        No   Male  23.0     USA   newyork           JOY   

  anonymous_brown_globs_that_come_in_black_and_orange_wrappers  \
0                                            DESPAIR             
1                                            DESPAIR             
2                                            DESPAIR             
3                                            DESPAIR             
4                                            DESPAIR             

  any_full_sized_candy_bar black_jacks Q6 | Bonkers (the candy)  ...  \
0                      JOY     DESPAIR                      NaN  ...   
1                      JOY         MEH                  DESPAIR  ...   
2                      JOY     DESPAIR                      NaN  ...   
3                      JOY         MEH                      MEH  ...   
4                      JOY     DESPAIR                      MEH  ...   

  Q6 | Trail Mix Q6 | Twix  \
0           MESH       JOY   
1        DESPAIR       JOY   
2           MESH       JOY   
3            MEH       JOY   
4        DESPAIR       JOY   

  Q6 | Vials of pure high fructose corn syrup, for main-lining into your vein  \
0                                            DESPAIR                            
1                                            DESPAIR                            
2                                            DESPAIR                            
3                                            DESPAIR                            
4                                                MEH                            

  Q6 | Vicodin Q6 | Whatchamacallit Bars Q6 | White Bread  \
0      DESPAIR                       JOY          DESPAIR   
1      DESPAIR                   DESPAIR          DESPAIR   
2      DESPAIR                       JOY          DESPAIR   
3          JOY                       JOY          DESPAIR   
4          JOY                       JOY          DESPAIR   

  Q6 | Whole Wheat anything Q6 | York Peppermint Patties           dress  \
0                   DESPAIR                          JOY  White and gold   
1                   DESPAIR                      DESPAIR  White and gold   
2                   DESPAIR                          JOY  White and gold   
3                   DESPAIR                      DESPAIR  White and gold   
4                   DESPAIR                          JOY  White and gold   

      day  
0  Friday  
1  Sunday  
2  Friday  
3  Sunday  
4  Friday  

[5 rows x 110 columns]

### 14 - write a summary about all the cleaning steps 

-Exploring data 
,  drop irrelevant data :useless
,  check if there are missing values
,  check duplicated values , drop it 
,   handling missing values , drop it , or fill it with (mean,mode,median,or other thing)
,   type conversion : convert culumn(age) from object type to numerical 
,   inconsistant data : column(country , state) deal with the same data but may receive it from different inputs so i tried make them the same
